# @name get-prompts
GET http://localhost:3333/prompts

###

# @name list-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
--boundary--

###

# @name create-transcription
POST http://localhost:3333/videos/cf02ac98-e5db-48b0-a2c7-30e9fec80553/transcription
Content-Type:  application/json

{
    "prompt": "pastor"
}
