# @name get-prompts
GET http://localhost:3333/prompts

###

# @name list-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="pastor-junior.mp3"
Content-Type: audio/mpeg

< ./pastor-junior.mp3
--boundary--

###

# @name create-transcription
POST http://localhost:3333/videos/4d4204fb-031a-477a-b063-c94d51fe13aa/transcription
Content-Type:  application/json

{
    "prompt": "pastor"
}
