# @name get-prompts
GET http://localhost:3333/prompts

###

# @name list-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
--boundary--

###

# @name create-transcription
POST http://localhost:3333/videos/cf02ac98-e5db-48b0-a2c7-30e9fec80553/transcription
Content-Type:  application/json

{
    "prompt": "clean architecture, ddd"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type:  application/json

{
    "videoId": "cf02ac98-e5db-48b0-a2c7-30e9fec80553",
    "temperature": 0.5,
    "template": "Gere um resumo sucinto da transcrição do video informada a seguir: '''{transcription}'''"
}

